helpers: move all complex tp shell script to the new tp_fun helper
Signed-off-by: Nicolas Morey <nmorey@suse.com>

diff --git a/helpers/common/10-nvme b/helpers/common/10-nvme
--- a/helpers/common/10-nvme
+++ b/helpers/common/10-nvme
@@ -15,54 +15,83 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+nvme_client_pre_cleanup()
+{
+    mount | grep /dev/nvme | awk '{ print \$1}' | xargs -I - umount - 2>/dev/null
+    nvme disconnect -n testnq
+    return 0
+}
+
+nvme_setup_server()
+{
+    local server_ip=$1
+    local LOOPD
+
+    # Pre cleanup. Ignore errors here
+    set +e
+    umount /tmp/hpc-test.mount 2>/dev/null
+    rm -Rf /tmp/hpc-test.mount /tmp/hpc-test.io 2>/dev/null
+    losetup -a | grep hpc-test.io | sed -e s/:.*// | xargs losetup -d
+    modprobe nvmet
+    nvmetcli clear
+    set -e
+
+    modprobe nvmet_rdma
+    LOOPD=$(losetup -f)
+    dd if=/dev/zero of=/tmp/hpc-test.io bs=1M count=256
+    losetup ${LOOPD} /tmp/hpc-test.io
+    mkfs.ext3 ${LOOPD}
+    mkdir /tmp/hpc-test.mount/
+    mount ${LOOPD} /tmp/hpc-test.mount/
+    dd if=/dev/urandom bs=1M count=64 of=/tmp/hpc-test.mount/input
+    umount  /tmp/hpc-test.mount
+    sed -i -e s/@MYIP@/"$server_ip"/ -e s%@BLK@%${LOOPD}% hpc-nvmet.json
+    nvmetcli restore hpc-nvmet.json
+}
+
+nvme_run_client()
+{
+    local server_ip=$1
+    local block_device
+
+    set +e
+    umount /tmp/srp-hpc-test 2>/dev/null
+    rm -Rf /tmp/srp-hpc-test 2>/dev/null
+    set -e
+
+    modprobe nvme_rdma
+    mkdir /tmp/srp-hpc-test
+    rm -f /etc/nvme/hostid
+    nvme discover -t rdma -a "$server_ip" -s 4420
+    nvme connect -t rdma -n testnqn -a "$server_ip" -s 4420
+    block_device=$(lsblk | grep nvme | awk "{ print \$1}")
+    echo $block_device
+    mount /dev/$block_device /tmp/srp-hpc-test
+    cp -R /tmp/srp-hpc-test/input /tmp/srp-hpc-test/output
+    diff -q /tmp/srp-hpc-test/input /tmp/srp-hpc-test/output
+    umount /tmp/srp-hpc-test
+    nvme disconnect -n testnqn
+    ! (lsblk | grep nvme)
+}
+
+nvme_test_and_clear_server()
+{
+    nvmetcli clear
+    mount -o loop /tmp/hpc-test.io /tmp/hpc-test.mount
+    diff -q /tmp/hpc-test.mount/input /tmp/hpc-test.mount/output
+    umount /tmp/hpc-test.mount
+    losetup -a | grep hpc-test.io | sed -e s/:.*// | xargs losetup -d
+}
+
 test_nvme(){
 	local server=$1
 	local server_ip=$2
 	local client=$3
 
-
-	# Cleanup old stuff just in case
-	tp $client "mount | grep /dev/nvme | awk '{ print \$1}' | xargs -I - umount - 2>/dev/null || true;
-	   		    nvme disconnect -n testnq || true"
-
 	cat helpers/ib/nvmet.json | tpq $server 'cat > hpc-nvmet.json'
 
-	tp $server 'umount /tmp/hpc-test.mount 2>/dev/null || true;
-	   		    rm -Rf /tmp/hpc-test.mount /tmp/hpc-test.io 2>/dev/null || true;
-	   		   	losetup -a | grep hpc-test.io | sed -e s/:.*// | xargs losetup -d || true;
-				modprobe nvmet;
-				nvmetcli clear || true;
-				modprobe nvmet_rdma &&
-				LOOPD=$(losetup -f) &&
-				dd if=/dev/zero of=/tmp/hpc-test.io bs=1M count=256 &&
-				losetup ${LOOPD} /tmp/hpc-test.io &&
-				mkfs.ext3 ${LOOPD} &&
-				mkdir /tmp/hpc-test.mount/ &&
-				mount ${LOOPD} /tmp/hpc-test.mount/ &&
-				dd if=/dev/urandom bs=1M count=64 of=/tmp/hpc-test.mount/input &&
-				umount  /tmp/hpc-test.mount &&
-				sed -i -e s/@MYIP@/'$server_ip'/ -e s%@BLK@%${LOOPD}% hpc-nvmet.json &&
-				nvmetcli restore hpc-nvmet.json'
-
-	tp $client 'umount /tmp/srp-hpc-test 2>/dev/null || true;
-	   		    rm -Rf /tmp/srp-hpc-test 2>/dev/null || true;
-				modprobe nvme_rdma &&
-				mkdir /tmp/srp-hpc-test &&
-				rm -f /etc/nvme/hostid &&
-				nvme discover -t rdma -a '$server_ip' -s 4420 &&
-				nvme connect -t rdma -n testnqn -a '$server_ip' -s 4420 &&
-				block_device=$(lsblk | grep nvme | awk "{ print \$1}") &&
-				echo $block_device &&
-				mount /dev/$block_device /tmp/srp-hpc-test &&
-				cp -R /tmp/srp-hpc-test/input /tmp/srp-hpc-test/output &&
-				diff -q /tmp/srp-hpc-test/input /tmp/srp-hpc-test/output&&
-				umount /tmp/srp-hpc-test &&
-				nvme disconnect -n testnqn &&
-				! (lsblk | grep nvme)'
-
-	tp $server 'nvmetcli clear &&
-	   		    mount -o loop /tmp/hpc-test.io /tmp/hpc-test.mount &&
-			   	diff -q /tmp/hpc-test.mount/input /tmp/hpc-test.mount/output &&
-				umount /tmp/hpc-test.mount &&
-				losetup -a | grep hpc-test.io | sed -e s/:.*// | xargs losetup -d'
+	tp_fun $client nvme_client_pre_cleanup
+	tp_fun $server nvme_setup_server $server_ip
+	tp_fun $client nvme_run_client $server_ip
+	tp_fun $server nvme_test_and_clear_server
 }
